### ISSUE TITLE
adjusting menu line

### ISSUE THREAD

**Issue by mvm26c** [godaddy/wp-ascension-theme#102]
Hi,

I'm new to coding.  I am trying to make the padding above and below the menu line much more narrow and trying to get all of the menu on one line.  Any thoughts of how can use additional css to accomplish this?  The website is www.new.matthewmorenotherapy.com

Thanks for any guidance.

**Comment by EvanHerman** [comment]
Hi @mvm26c 

You can adjust the top and bottom padding on the site header container with the following css:

```css
.site-header {
   padding: 10px 0;
}
```

You can add that to the customizers 'Additional CSS' section. To get there, from the dashboard, you can go to 'Appearance > Customize > Additional CSS' and paste the above CSS snippet into that area.

As for the menus all on the same line, it looks like you've achieved that.

Evan

**Comment by mvm26c** [comment]
Thank you Evan!  Worked perfectly.
