### ISSUE TITLE
trying to adjust footer widget padding

### ISSUE THREAD

**Issue by mvm26c** [godaddy/wp-ascension-theme#103]
Hi all, 

I'm trying to get the padding of the footer widget to be more narrow.  My website is www.matthewmorenotherapy.com.  Right now there is extra space above and below my address and the yelp button I added.  The current code that I tried is .footer-widget-area {
	padding: 10px 0;
}
Any guidance would be much appreciated.

**Comment by EvanHerman** [comment]
Hi @mvm26c 

Sorry for the delay. you can try:

```css
.footer-widget-area {
   margin-top: 45px;
}
```
