### ISSUE TITLE
Does Ascension support Bootstrap?

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#104]
Hi team,

I am looking to have a Bootstrap Carousel on the hero background of my website. While searching for it, I realized WordPress theme has to support bootstrap for that.

So, does Ascension support Bootstrap?

Thanks in advance for any help you could provide.

**Comment by EvanHerman** [comment]
@GodelMachine No, Ascension does not support bootstrap natively. We don't enqueue any bootstrap scripts or styles. You certainly could alongside the styles we've enqueued, but out of the bot it does not.
