### ISSUE TITLE
Relocate search bar + change it’s size on every page

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#105]
Hi Evan and team,

The search bar on my website is kind of dislocated, and is lingering quite unstrategically in the middle right on every page. 

I would like it to be situated at the upper right hand corner of every page. 

Furthermore, I would like to change it’s dimensions, and make it a wee bit smaller. 

Also, would you please advise me on how can I customize the appearance of search results? Right now, the search results occupy huge space and fonts are quite big too. I would like them to appear as sober as Google search results. 

Would you kindly impart me with your valuable guidance here.
Any feedback would be highly appreciated.
Thanks in advance for any help you could extend.
Memento Mori :)

**Comment by GodelMachine** [comment]
@EvanHerman  Would you kindly advsie me on how do I make this happen? 

Thanks in advance for any help which you could provide.

**Comment by GodelMachine** [comment]
@EvanHerman 

I tried using the Page Builder to change the location of the Search Box by just dragging it, however its not working. Would you please help out a buddy here? 

This is how it looks right now in the Page Builder - 

![image](https://user-images.githubusercontent.com/17872895/53319469-9ab35680-38f8-11e9-88d1-a6d9bffa6e2b.png)

Looks a bit ugly with the search bar stranded right in the middle of the site, and being so long.
I would like to make it smaller. 

Soliciting your advise.

**Comment by GodelMachine** [comment]
Also, in the above image, I am not able to place the search bar in the turquoise colored area. Would you please advise what am I getting wrong here? Thanks

**Comment by EvanHerman** [comment]
Please see: https://github.com/godaddy/wp-ascension-theme/issues/99

I would suggest posting in the WordPress.org support forums.
