### ISSUE TITLE
Where to place HTML snippet?

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#106]
Hi Evan and team,

I would like to use this plugin from this website - https://instant.page/ 
At the very beginning itself, it asks us to place an HTML snippet before </body>

Two doubts linger in my mind. Please be kind enough to address them - 

1) I don't understand where should I exactly paste this HTML snippet? Is it external CSS layout or in the Page Builder?

2) Should I be this for every single page? 

Thanks in advance for any help you could extend.

**Comment by EvanHerman** [comment]
@GodelMachine 

This code should be placed inside of a MU plugin and you should hook into `wp_head` and output that script tag there. Or Enqueue a script using `wp_enqueue_script()` in the `wp_enqueue_scripts` hook.

```php
/**
 * Enqueue instant page on every page of the website
 */
function enqueue_instant_page() {

   wp_enqueue_script( 'instant-page', '//instant.page/1.2.2', [ 'jquery' ], '1.2.2', true );

}
add_action( 'wp_enqueue_scripts', 'enqueue_instant_page' );
```

Codex Reference: https://developer.wordpress.org/reference/functions/wp_enqueue_script/
