### ISSUE TITLE
Remove header/hero image from all posts

### ISSUE THREAD

**Issue by TimperNan** [godaddy/wp-ascension-theme#108]
How can I remove the header / featured image box form the top of all posts?

e.g. http://www.meltdfw.com/2019/04/24/dave-benat-testimonial/

Thanks!
nancy

**Comment by ahalota** [comment]
In additional css, add this:

.hero {
	display: none;
}

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
