### ISSUE TITLE
pagination not working on mobile site

### ISSUE THREAD

**Issue by kathakartales** [godaddy/wp-ascension-theme#111]
pagination on desktop site:
![image](https://user-images.githubusercontent.com/54177781/63169180-c4516d00-c053-11e9-9d09-0dcf27a85add.png)

pagination on mobile site:
![mobile](https://user-images.githubusercontent.com/54177781/63169214-d59a7980-c053-11e9-8cc0-95d76346262e.jpg)

please advise if there is setting required for pagination to work on mobile sites.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
