### ISSUE TITLE
Nested Links Not Working On iPad

### ISSUE THREAD

**Issue by ajoeofalltrades** [godaddy/wp-ascension-theme#112]
There is no clear, clean way to have nested links drop down and appear on iPad (perhaps all tablets, I haven't had access to an Android tablet). Current behavior is to follow the link of the parent menu item on the first tap, so there is no chance for the child items to drop down and appear. (Primary menu appears as a row of links, not a hamburger menu, on iPad regardless of orientation.) I think the first tap should be considered what the "hover" action is on desktop, but I don't actually know what the UX standard is for drop down menus on tablet.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
