### ISSUE TITLE
Issues displaying the menu when it has sub-pages

### ISSUE THREAD

**Issue by alaskadream** [godaddy/wp-ascension-theme#113]
Having a menu with only one page in the menu "Welcome" then other pages as subpages of Welcome "About us" "Contact" and sub-pages of "About us" like "Team member 1" and "Team member 2"

So in a more visual way:

Welcome 
> About us (sub of Welcome)
>>Team member 1 (Sub of About us)
>>Team member 2 (Sub of About us)
> Contact (Sub of Welcome)

Screenshot: 
![Screenshot 2019-09-06 at 13 15 57](https://user-images.githubusercontent.com/54983861/64432013-eb7fe500-d0bb-11e9-9f70-d5f28a9558df.png)

causes the menu to fly off the page (off the content area) and be invisible (cut off).

Screenshot: 
![Screenshot 2019-09-06 at 13 17 34](https://user-images.githubusercontent.com/54983861/64432030-f5094d00-d0bb-11e9-9339-9717cacb0bf2.png)

The menu is set to float right, sub-entries also open to the right. However there's not enough room in the content area to display them. Instead of opening to the right and fly off the page if there's not enough room to the right they should open to the left.

How can I have submenus opening to the left so they don't get cut off when there's not enough room to the right? Or even better so they open to the right or left depending on whether there's room or not?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
