### ISSUE TITLE
Borders should not appear on hover in mobile nav

### ISSUE THREAD

**Issue by fjarrett** [godaddy/wp-ascension-theme#48]
<img width="330" alt="screen_shot_2016-08-26_at_2_24_20_pm" src="https://cloud.githubusercontent.com/assets/522158/18017779/dacbb74c-6b98-11e6-90b5-e3c123d71712.png">

**Comment by chriswallace** [comment]
I think the border color is being introduced by the customizer overrides from Primer. Will take a look but the likely fix is overriding/removing those border colors from the customizer array in the child theme.

**Comment by chriswallace** [comment]
@fjarrett It appears the border colors are being overridden [here](https://github.com/godaddy/wp-ascension-theme/blob/develop/functions.php#L171-L179). The trouble is that we should be overriding the color only on medium size and up. I don't think that's currently possible with the way the overrides work but we need to discuss how to fix this without getting too gnarly in our Sass files. Thoughts?

**Comment by fjarrett** [comment]
@chriswallace Just decided to throw the hover borders away on desktop menu items. Ignorance is bliss 😄
