### ISSUE TITLE
Fix styles on hero button

### ISSUE THREAD

**Issue by fjarrett** [godaddy/wp-ascension-theme#49]
There are `background` styles inside `style.css` that are overriding the custom color scheme CSS.

<img width="354" alt="screen shot 2016-09-08 at 1 47 06 am" src="https://cloud.githubusercontent.com/assets/522158/18339633/3eb100a6-7566-11e6-9f21-97c38f8a0e59.png">

**Comment by EvanHerman** [comment]
@jonathanbardo How should this behave? Should the `.hero` background inherit the base color for the selected color scheme?

It looks like the `.hero_background_color` key is missing from the colors array. Only the 'muted' color scheme has it defined.

**Comment by jonathanbardo** [comment]
@EvanHerman If it's missing then we need to add it. I'm pretty sure it was made to be inherited from the color scheme.

**Comment by EvanHerman** [comment]
@jonathanbardo I did some testing with the other child themes, and they too act the same way. When changing the color scheme, the hero background doesn't change except for when switching to 'muted'. The hero background theme_mod remains at #2c3845 at a 50% opacity.

If this needs to be updated, we'll have to add the `hero_background_color` key to the colors array on each of the child themes.

It may be worth investigating further to see if this is the intended behavior before updating each of them.

I went through and updated the colors array in ascension on [this branch](https://github.com/godaddy/wp-ascension-theme/tree/hero-background-color) if you want to take a look and test it before we commit the time.

**Comment by jonathanbardo** [comment]
@EvanHerman Does it look better when the color changes? Is this something we can fix in Primer?

**Comment by EvanHerman** [comment]
@jonathanbardo Primer actually does alter the hero background color when the color scheme is changed. It looks like it should be added to each child theme. The branch I worked on should be correct. I can make a PR for review.

**Comment by jonathanbardo** [comment]
Ok perfect, let's go that way then.
