### ISSUE TITLE
Option to remove "theme by" at bottom

### ISSUE THREAD

**Issue by allijames** [godaddy/wp-ascension-theme#58]
I like others have been searching for a way to easily remove the "theme by" text in the footer. It appears to be a php call, but from where??? This is not a request to simply change the author.

**Comment by fjarrett** [comment]
@allijames The Primer parent theme will be receiving an update in the near future that will allow this to be turned on/off inside the Customizer. For now, you can remove it with a little code in a custom must-use plugin. How-to and example: https://github.com/godaddy/wp-primer-theme/wiki/Customizing-Primer-with-hooks
