### ISSUE TITLE
Call to action button in top right of home page?

### ISSUE THREAD

**Issue by karaipc** [godaddy/wp-ascension-theme#59]
Is it possible to add a call to action button to the top right of this theme? It seems like empty real estate that could be used for a "call us" or "email us" button. Thanks!

**Comment by EvanHerman** [comment]
Hi @karaipc 

The call to action button is contained within the `.hero-inner` element generated by text widget inside of the hero widget area. 

If you want to add an additional call to action to the hero in a different location, you're best bet is to hook into the `primer_hero` action and add any additional markup you want and style it via CSS.

You'll want to delete the call to action from within the widget itself, and add the following snippet to your child themes **functions.php** file.

If you are uncomfortable editing .php files via FTP, you can use a third party plugin such as [My Custom Functions](https://wordpress.org/plugins/my-custom-functions/) to achieve the same thing.

Here is a very basic example, with inline styles, to demonstrate how it can be achieved:

```php
function custom_home_header_cta() {

	if ( ! is_front_page() ) {

		return;

	}

	echo '<a href="#" class="button" style="float:right;margin-top:0;">Call Us</a>';

}
add_action( 'primer_hero', 'custom_home_header_cta' );
```

#### Result

The final results will look similar to the following screenshot:

![Custom Call Home Hero to Action](https://cldup.com/vnci7R4y2Y.png)

Thanks,
Evan
