### ISSUE TITLE
Mobile Menu Functionality

### ISSUE THREAD

**Issue by tjcorke82** [godaddy/wp-ascension-theme#61]
I have previously seen the mobile menu problems seen in 'Primer' were fixed, yet the problem persists in Ascension - drop down menus do not drop down until a second 'tap' - can this be corrected?

**Comment by EvanHerman** [comment]
Hi @tjcorke82,

I can certainly take a look into the issue and figure out the best course of action for a fix.

Thanks for reporting the issue here.


Evan

**Comment by EvanHerman** [comment]
Hi @tjcorke82,

After some testing with the latest version of the theme I'm not able to replicate the issue on my end. It looks like the navigations are all functioning properly on my iPhone.

Do you have a test URL we can investigate? It's possible that you are running an older version of the theme where this issue was not yet fixed.

Thanks,
Evan

**Comment by tjcorke82** [comment]
Hi Evan,

The website it is used on is http://footballfedtas.com.au/.

Sadly the menu issue still remains on my iphone and through all other testing.

Tony.

**Comment by briannasue** [comment]
I too am having issues http://staydryohio.com/ nothing happens with menu when clicked.

**Comment by fjarrett** [comment]
@briannasue It looks like there is a plugin installed your site called "youtube-embed-plus" that may be causing conflicts with the menu functionality. Try deactivating it, clear your site cache, and test again.

**Comment by briannasue** [comment]
@fjarrett that was my first thought as well I tried deactivating all my plugins and testing. I did it again just now, just in case and still not working. Thanks!

**Comment by jonathanbardo** [comment]
@briannasue Actually I might know why this is happening. Did you remove the footer file in primer or did you override the footer file in the theme directly without calling `wp_footer`?

**Comment by briannasue** [comment]
@jonathanbardo yes that was it - that fixed it - thanks.
