### ISSUE TITLE
How to Replace Header

### ISSUE THREAD

**Issue by talkingmoon** [godaddy/wp-ascension-theme#62]
I am using the 'Wordpress Ascension theme/ Stylesheet' version 1.0.1 by Godaddy

I want to replace the static header image with a photo slider. I was hoping I could just replace the html 'header code' with the 'slider code' but I don't know really much about stylesheets to do this.

I would be really interested in hearing if you have any thoughts on the easiest way to do this.

**Comment by EvanHerman** [comment]
Hi @talkingmoon,

You would need to write some custom PHP to achieve this. CSS isn't going to be enough to get the job done.

Ideally, you'll want to setup an MU plugin where you can add your custom PHP functions to. We've setup some documentation and an outline on how to create an MU plugin here: https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html.

Once you have an MU plugin setup, you'll want to remove the hero container and then re-add a custom container with the slider code that you want to display. This needs to all be done within the MU plugin.

You can add the following code to your mu-plugin created above to help bump you in the right direction. Ideally, you'll want to replace `[slider-shortcode]` with the slider code that you would use to generate your slider.

```php
<?php
/**
* Plugin Name: My Customizations
* Description: Theme customizations and overrides.
* Author: Your Name
*/

/**
 * Remove the default primer header
 */
function remove_primer_header() {

    remove_action( 'primer_after_header', 'primer_add_hero', 7 );

    add_action( 'primer_after_header', 'primer_custom_hero', 7 );

}
add_action( 'template_redirect', 'remove_primer_header', 11 );

/**
 * Generate a new header container
 */
function primer_custom_hero() {

    printf(
       '<div class="hero">%s</div>',
       wp_kses_post( do_shortcode( '[slider-shortcode]' ) )
    );

}
```

You can save the mu-plugin and re-load your site to check if things are working properly. It is worth noting that the code above will change the header on all pages, and if you want to affect only the homepage you should consider using the `is_front_page()` conditional.

Example:
```php
 * Remove the default primer header
 */
function remove_primer_header() {

    if ( ! is_front_page() ) {

        return;

    }

    remove_action( 'primer_after_header', 'primer_add_hero', 7 );

    add_action( 'primer_after_header', 'primer_custom_hero', 7 );

}
add_action( 'template_redirect', 'remove_primer_header', 11 );
```

That should help get you going.

Evan

**Comment by talkingmoon** [comment]
Thank you, Evan.

I will try this out.
