### ISSUE TITLE
Remove Hero Text

### ISSUE THREAD

**Issue by github5905** [godaddy/wp-ascension-theme#72]
PLEASE is there anyone out there who can just tell me how to remove the hero text from all pages in my word press ascension theme?????

**Comment by github5905** [comment]
The forum at WP says GoDaddy owns the theme, and GD says to ask WP.  I just need someone to tell me how to do this please.

**Comment by EvanHerman** [comment]
Hi,

Are you referring to the page title? There is no other text in the hero.

You can either do so using custom CSS, entered into the customizer 'Additional CSS' section:

```css
.page-title {
   display: none;
}
```

or to remove the entire hero:

```css
.hero {
   display: none;
}
```

or, your second option is to create an MU plugin as [outlined in our documentation](https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html#how-to-create-a-must-use-plugin) and add the following code to it:

```php
/**
 * Remove the Ascension hero on all pages.
 *
 * @author GoDaddy
 */
function remove_ascension_hero() {

	remove_action( 'primer_after_header', 'primer_add_hero' );

}
add_action( 'template_redirect', 'remove_ascension_hero', 16 );
```

Both options will achieve what you are after.

Evan

**Comment by EvanHerman** [comment]
You will need to use CSS to tweak the hero size. You can try and tweak the element `#hero`.
