### ISSUE TITLE
Page title dissapeared

### ISSUE THREAD

**Issue by thorlax** [godaddy/wp-ascension-theme#77]
Added some custom css to move page title, menu and tagline around, worked fine, saved it, was fine, refreshed the page and it dissapeared, romoved custom css and still not there. uninstalled and reinstalled still nothing

**Comment by EvanHerman** [comment]
Hi @thorlax,

Do you have a link to a page where the title is not displaying? What CSS did you add/remove? Are you running a child theme where you may have possibly customized the template?

Evan

**Comment by thorlax** [comment]
Hi @EvanHerman 

thanks for responding, after trying to fix it for 2 days, I gave up, came back 3/4 hours later and the site title is back for some reason without me doing anything!

thanks anyway

**Comment by EvanHerman** [comment]
@thorlax No problem at all, sounds like it may have been a caching issue or something. Either way I'm glad it resolved itself. Have a great rest of your weekend!
