### ISSUE TITLE
Infinite scroll is not working with the Ascension theme

### ISSUE THREAD

**Issue by prajwalchandra** [godaddy/wp-ascension-theme#80]
Hi Team,

I see in the settings that infinite scroll is supported by Ascension theme, but it doesn't seem to work for me though it is enabled.

My site address: https://cartellers.com

Please have a look and help me fix it.

Regards,
Prajwal

**Comment by EvanHerman** [comment]
Hi @prajwalchandra 

Have you taken a look at the documentation pertaining to Jetpack infinite scroll that we have setup? https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/infinite-scroll-jetpack.html

That should help explain how to achieve things, if you have not yet followed along there.

Evan
