### ISSUE TITLE
Help Installing Demo Content

### ISSUE THREAD

**Issue by Jord1n** [godaddy/wp-ascension-theme#81]
Hello, I am new to WordPress and I can’t find any information on how to install the sample data that comes with the godaddy ascension theme.

I have installed WordPress and uploaded the theme but it is blank with no sample data. The theme file comes with no .xml file but it has two other files: package.json and package-lock.json.

Are these .json files the sample data files? and if they are how would I import them so that my site will look like the demo site?

Thanks for any help. It is much appreciated.

**Comment by EvanHerman** [comment]
Hi @Jord1n 

The package.json file and package-lock.json files are development files, which don't need to be included in the installation of the theme. Those files are used during the development process, but when the theme is built, bundled and shipped there are a number of files that are not included that are included here on github.

We do not currently have any sample data to import into the theme. The theme is a framework which requires you to populate it with the required data. Our demo site is just that, a demo of some sample content that we've thrown together to showcase the theme. We don't have that data exported into an easily transportable file.

Best,
Evan
