### ISSUE TITLE
CSS simple animation code + Sticker

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#85]
Hi Support Team,
 
 I have two issues
 
 1) I want a sticker on my website. Does Wordpress offer native stickers which I can put on my website? If not, which sticker plugin do you think would best serve my purpose. I have created an admission which students need to download tomorrow. I want to place it strategically on my website such that it is easily visible to everyone. That sticker will contain the link to the admission form. The sticker could be moving or flashing. 
 
 2) I would like to add some animation to the hero image on my homepage. Right now I have only one image on the homepage. I am not looking for any fancy animation as such, only that next image should roll in after 3 seconds of the previous image? I am also confused as to whether I should write this animation CSS code in "Customizable Additional CSS", or in the Appearance → Editor → Style.css? I am not inclined to install a 3rd party plugin, so would you kindly guide me on what CSS code should I use for a simple animation? 
 
 As of now, I have added only the following CSS code which shows one image.
 
 body.page-id-156 .hero {
  background: url( "http://www.jaihindjuniorcollege.com/wp-content/uploads/2017/06/Teachers-Day.jpg"
) 100%;
}

I am working on www.jaihindjuniorcollege.com

 Any help would be much appreciated.

Thanks :)

**Comment by EvanHerman** [comment]
WordPress does not offer native stickers. I suggest looking for a third part plugin to achieve this. As for your animations, this is also outside the scope of theme support. The forums here are generally just for bug reports. For theme customizations and additional development it's best to post in the general WordPress.org support forums:
https://wordpress.org/support/forum/wp-advanced/

The animation is going to take more work beyond some minor CSS tweaks. If you are unsure, or unfamiliar with the process, and need to feature complete quickly, you may want to hire someone who can get it done for you.

Evan
