### ISSUE TITLE
Remove hero from a specific page

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#87]
Hi team,

I would like to remove the hero container from this page - http://www.jaihindjuniorcollege.com/form/

My first approach was to find the page ID and add custom CSS to remove the hero container. But I couldn't locate the page ID, since the only page ID I got was 156, which belongs to homepage.

I looked up all my pages but did not find one by the name form. 

Reckon both of the above happened because I changed the permalink manually. 
Then I noticed that the only text on hero container was "Media", but couldn't find any page like "Media" in my pages.

http://www.jaihindjuniorcollege.com/form/ is viewable directly in Media tab and does not include itself in pages tab.

Would you kindly advise on what should I do ahead?

Thanks.

**Comment by EvanHerman** [comment]
You can just use CSS to hide the header on that page, otherwise you will need to customize the PHP templates contained within the theme.

The page you've linked to is no longer visible, but you can do something along the lines of:

```css
.body.page-id-123 .hero {
   display: none;
}
```

Evan
