### ISSUE TITLE
Two different permalink contents on same page

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#89]
Hi team

I wish to post two PDF files on the same page. I have added both the PDF files in the media library. 
But they have their own seperate pages whose links have been mentioned below.

http://www.jaihindjuniorcollege.com/admissionformacrobat12/

http://www.jaihindjuniorcollege.com/id_medical_escort-form/

I need to have both the files side by side, on the link - http://www.jaihindjuniorcollege.com/admissionformacrobat12/

Would you kindly advise me on how can I achieve this?

Thanks.

**Comment by EvanHerman** [comment]
Hi @GodelMachine ,

This is a bit outside the scope of theme support. You'll most likely want to find a third party plugin that will allow you to embed the PDF onto the page.

I've not used any plugin, so I can't provide you with any suggestions from experience, but from  a quick search the following came up:
https://wordpress.org/plugins/pdf-embedder/
