### ISSUE TITLE
Weird Bulleted Footer Menu

### ISSUE THREAD

**Issue by rbmarketer** [godaddy/wp-ascension-theme#90]
Hi everyone,

I can't find where to change the style of the footer menu. It's a bulleted list but it's centered so the bullets are to the left and the menu items are centered. I'd like it to just be a regular menu bar that goes across the bottom. 

Please help!

Thanks,

Rebecca

**Comment by EvanHerman** [comment]
Hi @rbmarketer 

Feel free to update to the latest release of Ascension. This was just patched up yesterday in the v1.1.3 release.

Evan
