### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#94]
Hi team,

Does Ascension have a search functionality?

I am trying to put a search button on my website wherein users can search any string they want and corresponding content from the site should show up.

My website is www.jaihindjuniorcollege.com

Please reply at your earliest convenience.

Thanks.

**Comment by EvanHerman** [comment]
Hi @GodelMachine 

You can add a search widget to a widgetized area within the theme from the widgets screen on the dashboard. You can get there from 'Appearance > Widgets'. You can drag the search widget to a sidebar, or another location in the theme.

Evan

**Comment by GodelMachine** [comment]
> 
> 
> Hi @GodelMachine
> 
> You can add a search widget to a widgetized area within the theme from the widgets screen on the dashboard. You can get there from 'Appearance > Widgets'. You can drag the search widget to a sidebar, or another location in the theme.
> 
> Evan

Hey Evan, thanks for your response. Which search widget would you recommend?

Thanks again :)

**Comment by EvanHerman** [comment]
@GodelMachine 

There is one built into WordPress out of the box. Otherwise you can install a third party plugin.

**Comment by GodelMachine** [comment]
@EvanHerman 

Thanks buddy.

**Comment by GodelMachine** [comment]
@EvanHerman 

Hey buddy, hate to bug you on a closed issue, but I think I removed my search functionality last year, I am a bit foggy about it.  

The search functionality appears on every other page except the home page, maybe I specifically removed it from there. Would you kindly suggest on how can I add it back? Ref - http://www.jaihindjuniorcollege.com/

I tried following the instructions on this page - https://codex.wordpress.org/Creating_a_Search_Page , but was not able to locate get_search_form() anywhere in style.css (Hope I am searching in the right place)

It also talks about page.php and index.php which I was not able to locate. 

Please reply at your earliest convenience. 

Thanks. Regards.

**Comment by GodelMachine** [comment]
Hi @EvanHerman 

I got the search functionality back using the page builder , but right now its right in the middle.

I would like it to be in the top right corner in reduce the dimensions of the search box too.

Would you kindly advise me on how can I do that?

Thanks. Regards.

![image](https://user-images.githubusercontent.com/17872895/46489980-61345e80-c824-11e8-87fa-49cb6ff3942f.png)
