### ISSUE TITLE
Home page won't span full width

### ISSUE THREAD

**Issue by jcsllc1979** [godaddy/wp-ascension-theme#95]
I'm using the Ascension theme.  I built my website many months ago.  One day, I noticed that my home page had changed from what I had originally done.  My other pages are exactly as I had set them up, but my home page is not correct.  I cannot get my columns/rows to span the width of the page.  The first picture is of the home page and the second is how I want the home page to look.  Can someone help me?  The url to my site is www.johnstonschimney.com
[website.docx](https://github.com/godaddy/wp-ascension-theme/files/2398585/website.docx)

**Comment by EvanHerman** [comment]
Hi @jcsllc1979 

Have you tried changing the page width value on the edit page screen?

<img src="https://cldup.com/ZNLkIXK7q9.png" width="75%" />
