### ISSUE TITLE
Unable to figure out adding Adsense code to this theme

### ISSUE THREAD

**Issue by metallicwarden** [godaddy/wp-ascension-theme#96]
Hi,

I'm trying to figure out to add the adsense code to this theme. Adsense recommends adding the script between the <head> and </head> tags. Not able to find these on the theme editor - says theme uses parent theme "primer".

Need insights

**Comment by EvanHerman** [comment]
Hi @metallicwarden 

There is nothing built into the plugin to allow for this, but there are a number of plugins that can help you insert your Google adsense code into the appropriate location.

Feel free to read through the Google documentation or this wpbeginner tutorial:
https://support.google.com/adsense/answer/7527509?hl=en
https://www.wpbeginner.com/beginners-guide/how-to-add-google-adsense-to-your-wordpress-site/
