### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#98]
Hi team

I would like to add a carousel such as this (w3schools link below) in my hero image. Basically, I want to have an animation hero on my home page and will have some pictures.

Would the code on this site help me achieve what I want? - https://www.w3schools.com/bootstrap/bootstrap_carousel.asp

I would also like the hero image to be roughly of this size. However, right now, its consuming the entire space from left to right.

My website is - www.jaihindjuniorcollege.com

Would you please advise me on this?

Thanks. Regards.

**Comment by EvanHerman** [comment]
@GodelMachine 

This is outside the scope of support here. This is getting into the realm of custom development work, and something you would most likely want to hire someone for. This is a little more advanced then just telling you where to paste some code into your theme. For that I would recommend you post this question in the WOrdPress.org support forums under 'Developing with WordPress'.

https://wordpress.org/support/forum/wp-advanced/
