### ISSUE TITLE
Resize Hero Image

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#99]
Hi team,

I would like to resize Hero image on my site.
Right now its consuming end to end viz. from left screen of the website to the extreme right end.

Reckon I set block-size - 100% somewhere in CSS, but I not so certain about it now.

I would like my Hero image to look something like the one in the below image.

![image](https://user-images.githubusercontent.com/17872895/46581934-cb841380-ca5d-11e8-96b2-15d81bb5fd88.png)

Please guide me here. 

Thanks in advance. Regards.

**Comment by GodelMachine** [comment]
FYI - My website is www.jaihindjuniorcollege.com

**Comment by EvanHerman** [comment]
I'd suggest that you post these question over in the WordPress.org support forum. These are generally development questions, while these forums are for tracking bugs or issues with the plugin itself.

https://wordpress.org/support/forum/wp-advanced/
